name: Publish résumé to GitHub Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Publish CV"
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Compile CV
      run: |
          sudo apt-get update > /dev/null
          sudo apt-get -qq install wget > /dev/null
          wget -q -O pdf2htmlEX.deb https://github.com/pdf2htmlEX/pdf2htmlEX/releases/download/continuous/pdf2htmlEX-0.18.8.rc2-master-20200820-ubuntu-20.04-x86_64.deb > /dev/null
          sudo apt-get -qq install texlive-full texlive-xetex texlive-luatex ttfautohint ./pdf2htmlEX.deb fonts-ebgaramond fonts-ebgaramond-extra > /dev/null
          wget -q -O EBGaramond.zip https://bitbucket.org/georgd/eb-garamond/downloads/EBGaramond-0.016.zip > /dev/null
          unzip EBGaramond.zip > /dev/null
          mkdir -p /usr/share/fonts/opentype/ebgaramond/
          cp ./EBGaramond-0.016/otf/*.otf /usr/share/fonts/opentype/ebgaramond/ > /dev/null
          rm -f ./pdf2htmlEX.deb > /dev/null
          rm -rf ./EBGaramond-0.016 > /dev/null
          rm -f ./EBGaramond.zip > /dev/null
          xelatex resume.tex
          mv -f resume.pdf 'Emil Sayahi.pdf'
          ./make_html.sh
    - name: Commit changes, if any
      run: |
        git config --global user.name 'Emil Sayahi'
        git config --global user.email 'Dirout@users.noreply.github.com'
        git diff --quiet && git diff --staged --quiet || git commit -am "Update HTML file"
        git push
